//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomerServiceReference.ResponseWithContentOfCustomerDC1nk_PiFui))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomerServiceReference.ResponseWithContentOfArrayOfCustomerDC1nk_PiFui))]
    public partial class Response : object
    {
        
        private string MessageField;
        
        private int StatusCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithContentOfCustomerDC1nk_PiFui", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class ResponseWithContentOfCustomerDC1nk_PiFui : CustomerServiceReference.Response
    {
        
        private CustomerServiceReference.CustomerDC DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomerServiceReference.CustomerDC Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithContentOfArrayOfCustomerDC1nk_PiFui", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class ResponseWithContentOfArrayOfCustomerDC1nk_PiFui : CustomerServiceReference.Response
    {
        
        private CustomerServiceReference.CustomerDC[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomerServiceReference.CustomerDC[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDC", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class CustomerDC : object
    {
        
        private CustomerServiceReference.BankAccountDC[] BankAccountsField;
        
        private string BirthdateField;
        
        private string HouseAdressField;
        
        private string MailField;
        
        private string NameField;
        
        private CustomerServiceReference.PersonalReferenceDC[] PersonalReferencesField;
        
        private string PhoneNumber1Field;
        
        private string PhoneNumber2Field;
        
        private string RfcField;
        
        private bool StateField;
        
        private string WorkAddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomerServiceReference.BankAccountDC[] BankAccounts
        {
            get
            {
                return this.BankAccountsField;
            }
            set
            {
                this.BankAccountsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Birthdate
        {
            get
            {
                return this.BirthdateField;
            }
            set
            {
                this.BirthdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseAdress
        {
            get
            {
                return this.HouseAdressField;
            }
            set
            {
                this.HouseAdressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail
        {
            get
            {
                return this.MailField;
            }
            set
            {
                this.MailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomerServiceReference.PersonalReferenceDC[] PersonalReferences
        {
            get
            {
                return this.PersonalReferencesField;
            }
            set
            {
                this.PersonalReferencesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber1
        {
            get
            {
                return this.PhoneNumber1Field;
            }
            set
            {
                this.PhoneNumber1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber2
        {
            get
            {
                return this.PhoneNumber2Field;
            }
            set
            {
                this.PhoneNumber2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rfc
        {
            get
            {
                return this.RfcField;
            }
            set
            {
                this.RfcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkAddress
        {
            get
            {
                return this.WorkAddressField;
            }
            set
            {
                this.WorkAddressField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankAccountDC", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class BankAccountDC : object
    {
        
        private string ClabeField;
        
        private string CustomerRfcField;
        
        private int IdField;
        
        private CustomerServiceReference.BankAccountType PurposeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clabe
        {
            get
            {
                return this.ClabeField;
            }
            set
            {
                this.ClabeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerRfc
        {
            get
            {
                return this.CustomerRfcField;
            }
            set
            {
                this.CustomerRfcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomerServiceReference.BankAccountType Purpose
        {
            get
            {
                return this.PurposeField;
            }
            set
            {
                this.PurposeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonalReferenceDC", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class PersonalReferenceDC : object
    {
        
        private string CustomerRfcField;
        
        private int IdField;
        
        private string NameField;
        
        private string PhoneNumberField;
        
        private string RelationshipField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerRfc
        {
            get
            {
                return this.CustomerRfcField;
            }
            set
            {
                this.CustomerRfcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Relationship
        {
            get
            {
                return this.RelationshipField;
            }
            set
            {
                this.RelationshipField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankAccountType", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public enum BankAccountType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Receive = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Collect = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerServiceReference.ICustomerService")]
    public interface ICustomerService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomersByPagination", ReplyAction="http://tempuri.org/ICustomerService/GetCustomersByPaginationResponse")]
        CustomerServiceReference.ResponseWithContentOfArrayOfCustomerDC1nk_PiFui GetCustomersByPagination(int pageSize, string markRfc, bool next);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomersByPagination", ReplyAction="http://tempuri.org/ICustomerService/GetCustomersByPaginationResponse")]
        System.Threading.Tasks.Task<CustomerServiceReference.ResponseWithContentOfArrayOfCustomerDC1nk_PiFui> GetCustomersByPaginationAsync(int pageSize, string markRfc, bool next);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomerByRfc", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerByRfcResponse")]
        CustomerServiceReference.ResponseWithContentOfCustomerDC1nk_PiFui GetCustomerByRfc(string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomerByRfc", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerByRfcResponse")]
        System.Threading.Tasks.Task<CustomerServiceReference.ResponseWithContentOfCustomerDC1nk_PiFui> GetCustomerByRfcAsync(string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/AddCustomer", ReplyAction="http://tempuri.org/ICustomerService/AddCustomerResponse")]
        CustomerServiceReference.Response AddCustomer(CustomerServiceReference.CustomerDC customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/AddCustomer", ReplyAction="http://tempuri.org/ICustomerService/AddCustomerResponse")]
        System.Threading.Tasks.Task<CustomerServiceReference.Response> AddCustomerAsync(CustomerServiceReference.CustomerDC customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateCustomerPersonalInformation", ReplyAction="http://tempuri.org/ICustomerService/UpdateCustomerPersonalInformationResponse")]
        CustomerServiceReference.Response UpdateCustomerPersonalInformation(CustomerServiceReference.CustomerDC customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateCustomerPersonalInformation", ReplyAction="http://tempuri.org/ICustomerService/UpdateCustomerPersonalInformationResponse")]
        System.Threading.Tasks.Task<CustomerServiceReference.Response> UpdateCustomerPersonalInformationAsync(CustomerServiceReference.CustomerDC customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateCustomerBankAccount", ReplyAction="http://tempuri.org/ICustomerService/UpdateCustomerBankAccountResponse")]
        CustomerServiceReference.Response UpdateCustomerBankAccount(CustomerServiceReference.BankAccountDC bankAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateCustomerBankAccount", ReplyAction="http://tempuri.org/ICustomerService/UpdateCustomerBankAccountResponse")]
        System.Threading.Tasks.Task<CustomerServiceReference.Response> UpdateCustomerBankAccountAsync(CustomerServiceReference.BankAccountDC bankAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateCustomerPersonalReference", ReplyAction="http://tempuri.org/ICustomerService/UpdateCustomerPersonalReferenceResponse")]
        CustomerServiceReference.Response UpdateCustomerPersonalReference(CustomerServiceReference.PersonalReferenceDC personalReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateCustomerPersonalReference", ReplyAction="http://tempuri.org/ICustomerService/UpdateCustomerPersonalReferenceResponse")]
        System.Threading.Tasks.Task<CustomerServiceReference.Response> UpdateCustomerPersonalReferenceAsync(CustomerServiceReference.PersonalReferenceDC personalReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateCustomerState", ReplyAction="http://tempuri.org/ICustomerService/UpdateCustomerStateResponse")]
        CustomerServiceReference.Response UpdateCustomerState(string rfc, bool state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateCustomerState", ReplyAction="http://tempuri.org/ICustomerService/UpdateCustomerStateResponse")]
        System.Threading.Tasks.Task<CustomerServiceReference.Response> UpdateCustomerStateAsync(string rfc, bool state);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ICustomerServiceChannel : CustomerServiceReference.ICustomerService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<CustomerServiceReference.ICustomerService>, CustomerServiceReference.ICustomerService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CustomerServiceClient() : 
                base(CustomerServiceClient.GetDefaultBinding(), CustomerServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICustomerService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CustomerServiceClient.GetBindingForEndpoint(endpointConfiguration), CustomerServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CustomerServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CustomerServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public CustomerServiceReference.ResponseWithContentOfArrayOfCustomerDC1nk_PiFui GetCustomersByPagination(int pageSize, string markRfc, bool next)
        {
            return base.Channel.GetCustomersByPagination(pageSize, markRfc, next);
        }
        
        public System.Threading.Tasks.Task<CustomerServiceReference.ResponseWithContentOfArrayOfCustomerDC1nk_PiFui> GetCustomersByPaginationAsync(int pageSize, string markRfc, bool next)
        {
            return base.Channel.GetCustomersByPaginationAsync(pageSize, markRfc, next);
        }
        
        public CustomerServiceReference.ResponseWithContentOfCustomerDC1nk_PiFui GetCustomerByRfc(string rfc)
        {
            return base.Channel.GetCustomerByRfc(rfc);
        }
        
        public System.Threading.Tasks.Task<CustomerServiceReference.ResponseWithContentOfCustomerDC1nk_PiFui> GetCustomerByRfcAsync(string rfc)
        {
            return base.Channel.GetCustomerByRfcAsync(rfc);
        }
        
        public CustomerServiceReference.Response AddCustomer(CustomerServiceReference.CustomerDC customer)
        {
            return base.Channel.AddCustomer(customer);
        }
        
        public System.Threading.Tasks.Task<CustomerServiceReference.Response> AddCustomerAsync(CustomerServiceReference.CustomerDC customer)
        {
            return base.Channel.AddCustomerAsync(customer);
        }
        
        public CustomerServiceReference.Response UpdateCustomerPersonalInformation(CustomerServiceReference.CustomerDC customer)
        {
            return base.Channel.UpdateCustomerPersonalInformation(customer);
        }
        
        public System.Threading.Tasks.Task<CustomerServiceReference.Response> UpdateCustomerPersonalInformationAsync(CustomerServiceReference.CustomerDC customer)
        {
            return base.Channel.UpdateCustomerPersonalInformationAsync(customer);
        }
        
        public CustomerServiceReference.Response UpdateCustomerBankAccount(CustomerServiceReference.BankAccountDC bankAccount)
        {
            return base.Channel.UpdateCustomerBankAccount(bankAccount);
        }
        
        public System.Threading.Tasks.Task<CustomerServiceReference.Response> UpdateCustomerBankAccountAsync(CustomerServiceReference.BankAccountDC bankAccount)
        {
            return base.Channel.UpdateCustomerBankAccountAsync(bankAccount);
        }
        
        public CustomerServiceReference.Response UpdateCustomerPersonalReference(CustomerServiceReference.PersonalReferenceDC personalReference)
        {
            return base.Channel.UpdateCustomerPersonalReference(personalReference);
        }
        
        public System.Threading.Tasks.Task<CustomerServiceReference.Response> UpdateCustomerPersonalReferenceAsync(CustomerServiceReference.PersonalReferenceDC personalReference)
        {
            return base.Channel.UpdateCustomerPersonalReferenceAsync(personalReference);
        }
        
        public CustomerServiceReference.Response UpdateCustomerState(string rfc, bool state)
        {
            return base.Channel.UpdateCustomerState(rfc, state);
        }
        
        public System.Threading.Tasks.Task<CustomerServiceReference.Response> UpdateCustomerStateAsync(string rfc, bool state)
        {
            return base.Channel.UpdateCustomerStateAsync(rfc, state);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICustomerService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICustomerService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:5001/CustomerService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CustomerServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICustomerService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CustomerServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICustomerService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICustomerService,
        }
    }
}
