//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SessionServiceReference.ResponseWithContentOfEmployeeefOWEHwa))]
    public partial class Response : object
    {
        
        private string MessageField;
        
        private int StatusCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithContentOfEmployeeefOWEHwa", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class ResponseWithContentOfEmployeeefOWEHwa : SessionServiceReference.Response
    {
        
        private SessionServiceReference.Employee DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.Employee Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/Data_Access.Entities")]
    public partial class Employee : object
    {
        
        private SessionServiceReference.CreditCondition[] CreditConditionsField;
        
        private SessionServiceReference.CreditPolicy[] CreditPoliciesField;
        
        private SessionServiceReference.Credit[] CreditsField;
        
        private SessionServiceReference.Document[] DocumentsField;
        
        private SessionServiceReference.Payment[] PaymentsField;
        
        private string addressField;
        
        private SessionServiceReference.DateOnly birthdayField;
        
        private int idField;
        
        private string mailField;
        
        private string nameField;
        
        private string passwordField;
        
        private string phoneNumberField;
        
        private string roleField;
        
        private SessionServiceReference.Subsidiary sucursalField;
        
        private int sucursalIdField;
        
        private string userField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.CreditCondition[] CreditConditions
        {
            get
            {
                return this.CreditConditionsField;
            }
            set
            {
                this.CreditConditionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.CreditPolicy[] CreditPolicies
        {
            get
            {
                return this.CreditPoliciesField;
            }
            set
            {
                this.CreditPoliciesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.Credit[] Credits
        {
            get
            {
                return this.CreditsField;
            }
            set
            {
                this.CreditsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.Document[] Documents
        {
            get
            {
                return this.DocumentsField;
            }
            set
            {
                this.DocumentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.Payment[] Payments
        {
            get
            {
                return this.PaymentsField;
            }
            set
            {
                this.PaymentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.DateOnly birthday
        {
            get
            {
                return this.birthdayField;
            }
            set
            {
                this.birthdayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail
        {
            get
            {
                return this.mailField;
            }
            set
            {
                this.mailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.Subsidiary sucursal
        {
            get
            {
                return this.sucursalField;
            }
            set
            {
                this.sucursalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sucursalId
        {
            get
            {
                return this.sucursalIdField;
            }
            set
            {
                this.sucursalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateOnly", Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial struct DateOnly
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subsidiary", Namespace="http://schemas.datacontract.org/2004/07/Data_Access.Entities")]
    public partial class Subsidiary : object
    {
        
        private string AddressField;
        
        private SessionServiceReference.Employee[] EmployeesField;
        
        private int idField;
        
        private bool stateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.Employee[] Employees
        {
            get
            {
                return this.EmployeesField;
            }
            set
            {
                this.EmployeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCondition", Namespace="http://schemas.datacontract.org/2004/07/Data_Access.Entities")]
    public partial class CreditCondition : object
    {
        
        private SessionServiceReference.Credit[] CreditsField;
        
        private int IVAField;
        
        private int idField;
        
        private int interestRateField;
        
        private int paymentsPerMonthField;
        
        private int registrerField;
        
        private SessionServiceReference.Employee registrerNavigationField;
        
        private bool stateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.Credit[] Credits
        {
            get
            {
                return this.CreditsField;
            }
            set
            {
                this.CreditsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IVA
        {
            get
            {
                return this.IVAField;
            }
            set
            {
                this.IVAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int interestRate
        {
            get
            {
                return this.interestRateField;
            }
            set
            {
                this.interestRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int paymentsPerMonth
        {
            get
            {
                return this.paymentsPerMonthField;
            }
            set
            {
                this.paymentsPerMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int registrer
        {
            get
            {
                return this.registrerField;
            }
            set
            {
                this.registrerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.Employee registrerNavigation
        {
            get
            {
                return this.registrerNavigationField;
            }
            set
            {
                this.registrerNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditPolicy", Namespace="http://schemas.datacontract.org/2004/07/Data_Access.Entities")]
    public partial class CreditPolicy : object
    {
        
        private string descriptionField;
        
        private SessionServiceReference.DateOnly effectiveDateField;
        
        private int idField;
        
        private int registrerField;
        
        private SessionServiceReference.Employee registrerNavigationField;
        
        private bool stateField;
        
        private string titleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.DateOnly effectiveDate
        {
            get
            {
                return this.effectiveDateField;
            }
            set
            {
                this.effectiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int registrer
        {
            get
            {
                return this.registrerField;
            }
            set
            {
                this.registrerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.Employee registrerNavigation
        {
            get
            {
                return this.registrerNavigationField;
            }
            set
            {
                this.registrerNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credit", Namespace="http://schemas.datacontract.org/2004/07/Data_Access.Entities")]
    public partial class Credit : object
    {
        
        private SessionServiceReference.Document[] DocumentsField;
        
        private SessionServiceReference.Payment[] PaymentsField;
        
        private string beneficiaryField;
        
        private SessionServiceReference.Client beneficiaryNavigationField;
        
        private int capitalField;
        
        private SessionServiceReference.CreditCondition conditionField;
        
        private int conditionIdField;
        
        private byte durationField;
        
        private int idField;
        
        private int registrerField;
        
        private SessionServiceReference.Employee registrerNavigationField;
        
        private string stateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.Document[] Documents
        {
            get
            {
                return this.DocumentsField;
            }
            set
            {
                this.DocumentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.Payment[] Payments
        {
            get
            {
                return this.PaymentsField;
            }
            set
            {
                this.PaymentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string beneficiary
        {
            get
            {
                return this.beneficiaryField;
            }
            set
            {
                this.beneficiaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.Client beneficiaryNavigation
        {
            get
            {
                return this.beneficiaryNavigationField;
            }
            set
            {
                this.beneficiaryNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int capital
        {
            get
            {
                return this.capitalField;
            }
            set
            {
                this.capitalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.CreditCondition condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int conditionId
        {
            get
            {
                return this.conditionIdField;
            }
            set
            {
                this.conditionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int registrer
        {
            get
            {
                return this.registrerField;
            }
            set
            {
                this.registrerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.Employee registrerNavigation
        {
            get
            {
                return this.registrerNavigationField;
            }
            set
            {
                this.registrerNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://schemas.datacontract.org/2004/07/Data_Access.Entities")]
    public partial class Document : object
    {
        
        private SessionServiceReference.Credit creditField;
        
        private int creditIdField;
        
        private SessionServiceReference.RequiredDocumentation documentationField;
        
        private int documentationIdField;
        
        private int idField;
        
        private string nameField;
        
        private int registrerField;
        
        private SessionServiceReference.Employee registrerNavigationField;
        
        private System.DateTime registryDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.Credit credit
        {
            get
            {
                return this.creditField;
            }
            set
            {
                this.creditField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int creditId
        {
            get
            {
                return this.creditIdField;
            }
            set
            {
                this.creditIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.RequiredDocumentation documentation
        {
            get
            {
                return this.documentationField;
            }
            set
            {
                this.documentationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int documentationId
        {
            get
            {
                return this.documentationIdField;
            }
            set
            {
                this.documentationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int registrer
        {
            get
            {
                return this.registrerField;
            }
            set
            {
                this.registrerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.Employee registrerNavigation
        {
            get
            {
                return this.registrerNavigationField;
            }
            set
            {
                this.registrerNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime registryDate
        {
            get
            {
                return this.registryDateField;
            }
            set
            {
                this.registryDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/Data_Access.Entities")]
    public partial class Payment : object
    {
        
        private decimal amountField;
        
        private SessionServiceReference.DateOnly collectionDateField;
        
        private SessionServiceReference.Credit creditField;
        
        private int creditIdField;
        
        private int idField;
        
        private int registrerField;
        
        private SessionServiceReference.Employee registrerNavigationField;
        
        private string stateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.DateOnly collectionDate
        {
            get
            {
                return this.collectionDateField;
            }
            set
            {
                this.collectionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.Credit credit
        {
            get
            {
                return this.creditField;
            }
            set
            {
                this.creditField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int creditId
        {
            get
            {
                return this.creditIdField;
            }
            set
            {
                this.creditIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int registrer
        {
            get
            {
                return this.registrerField;
            }
            set
            {
                this.registrerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.Employee registrerNavigation
        {
            get
            {
                return this.registrerNavigationField;
            }
            set
            {
                this.registrerNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/Data_Access.Entities")]
    public partial class Client : object
    {
        
        private SessionServiceReference.BankAccount[] BankAccountsField;
        
        private SessionServiceReference.Credit[] CreditsField;
        
        private SessionServiceReference.DateOnly birthdayField;
        
        private string houseAddressField;
        
        private string mailField;
        
        private string nameField;
        
        private string phoneNumber1Field;
        
        private string phoneNumber2Field;
        
        private string rfcField;
        
        private bool stateField;
        
        private string workAddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.BankAccount[] BankAccounts
        {
            get
            {
                return this.BankAccountsField;
            }
            set
            {
                this.BankAccountsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.Credit[] Credits
        {
            get
            {
                return this.CreditsField;
            }
            set
            {
                this.CreditsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.DateOnly birthday
        {
            get
            {
                return this.birthdayField;
            }
            set
            {
                this.birthdayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string houseAddress
        {
            get
            {
                return this.houseAddressField;
            }
            set
            {
                this.houseAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail
        {
            get
            {
                return this.mailField;
            }
            set
            {
                this.mailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber1
        {
            get
            {
                return this.phoneNumber1Field;
            }
            set
            {
                this.phoneNumber1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber2
        {
            get
            {
                return this.phoneNumber2Field;
            }
            set
            {
                this.phoneNumber2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rfc
        {
            get
            {
                return this.rfcField;
            }
            set
            {
                this.rfcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string workAddress
        {
            get
            {
                return this.workAddressField;
            }
            set
            {
                this.workAddressField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequiredDocumentation", Namespace="http://schemas.datacontract.org/2004/07/Data_Access.Entities")]
    public partial class RequiredDocumentation : object
    {
        
        private SessionServiceReference.Document[] DocumentsField;
        
        private string fileTypeField;
        
        private int idField;
        
        private string nameField;
        
        private bool stateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.Document[] Documents
        {
            get
            {
                return this.DocumentsField;
            }
            set
            {
                this.DocumentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fileType
        {
            get
            {
                return this.fileTypeField;
            }
            set
            {
                this.fileTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankAccount", Namespace="http://schemas.datacontract.org/2004/07/Data_Access.Entities")]
    public partial class BankAccount : object
    {
        
        private string clabeField;
        
        private SessionServiceReference.Client clientField;
        
        private string clientIdField;
        
        private int idField;
        
        private string purposeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clabe
        {
            get
            {
                return this.clabeField;
            }
            set
            {
                this.clabeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SessionServiceReference.Client client
        {
            get
            {
                return this.clientField;
            }
            set
            {
                this.clientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clientId
        {
            get
            {
                return this.clientIdField;
            }
            set
            {
                this.clientIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string purpose
        {
            get
            {
                return this.purposeField;
            }
            set
            {
                this.purposeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SessionServiceReference.ISessionService")]
    public interface ISessionService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/Login", ReplyAction="http://tempuri.org/ISessionService/LoginResponse")]
        SessionServiceReference.ResponseWithContentOfEmployeeefOWEHwa Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/Login", ReplyAction="http://tempuri.org/ISessionService/LoginResponse")]
        System.Threading.Tasks.Task<SessionServiceReference.ResponseWithContentOfEmployeeefOWEHwa> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/GetAccountInfo", ReplyAction="http://tempuri.org/ISessionService/GetAccountInfoResponse")]
        SessionServiceReference.ResponseWithContentOfEmployeeefOWEHwa GetAccountInfo(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/GetAccountInfo", ReplyAction="http://tempuri.org/ISessionService/GetAccountInfoResponse")]
        System.Threading.Tasks.Task<SessionServiceReference.ResponseWithContentOfEmployeeefOWEHwa> GetAccountInfoAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/Logout", ReplyAction="http://tempuri.org/ISessionService/LogoutResponse")]
        SessionServiceReference.Response Logout(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/Logout", ReplyAction="http://tempuri.org/ISessionService/LogoutResponse")]
        System.Threading.Tasks.Task<SessionServiceReference.Response> LogoutAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ISessionServiceChannel : SessionServiceReference.ISessionService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class SessionServiceClient : System.ServiceModel.ClientBase<SessionServiceReference.ISessionService>, SessionServiceReference.ISessionService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SessionServiceClient() : 
                base(SessionServiceClient.GetDefaultBinding(), SessionServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISessionService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SessionServiceClient.GetBindingForEndpoint(endpointConfiguration), SessionServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SessionServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SessionServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public SessionServiceReference.ResponseWithContentOfEmployeeefOWEHwa Login(string username, string password)
        {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<SessionServiceReference.ResponseWithContentOfEmployeeefOWEHwa> LoginAsync(string username, string password)
        {
            return base.Channel.LoginAsync(username, password);
        }
        
        public SessionServiceReference.ResponseWithContentOfEmployeeefOWEHwa GetAccountInfo(string username)
        {
            return base.Channel.GetAccountInfo(username);
        }
        
        public System.Threading.Tasks.Task<SessionServiceReference.ResponseWithContentOfEmployeeefOWEHwa> GetAccountInfoAsync(string username)
        {
            return base.Channel.GetAccountInfoAsync(username);
        }
        
        public SessionServiceReference.Response Logout(string username)
        {
            return base.Channel.Logout(username);
        }
        
        public System.Threading.Tasks.Task<SessionServiceReference.Response> LogoutAsync(string username)
        {
            return base.Channel.LogoutAsync(username);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISessionService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISessionService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:5001/SessionService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SessionServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISessionService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SessionServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISessionService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISessionService,
        }
    }
}
