//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PaymentServiceReference.ResponseWithContentOfArrayOfPaymentLayoutDC1nk_PiFui))]
    public partial class Response : object
    {
        
        private string MessageField;
        
        private int StatusCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithContentOfArrayOfPaymentLayoutDC1nk_PiFui", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class ResponseWithContentOfArrayOfPaymentLayoutDC1nk_PiFui : PaymentServiceReference.Response
    {
        
        private PaymentServiceReference.PaymentLayoutDC[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PaymentServiceReference.PaymentLayoutDC[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentLayoutDC", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class PaymentLayoutDC : object
    {
        
        private decimal AmountField;
        
        private string BankAccountClabeField;
        
        private string ClientNameField;
        
        private string CollectionDateField;
        
        private int FolioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankAccountClabe
        {
            get
            {
                return this.BankAccountClabeField;
            }
            set
            {
                this.BankAccountClabeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName
        {
            get
            {
                return this.ClientNameField;
            }
            set
            {
                this.ClientNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollectionDate
        {
            get
            {
                return this.CollectionDateField;
            }
            set
            {
                this.CollectionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Folio
        {
            get
            {
                return this.FolioField;
            }
            set
            {
                this.FolioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentDC", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class PaymentDC : object
    {
        
        private decimal AmountField;
        
        private string CollectionDateField;
        
        private int CreditIdField;
        
        private int IdField;
        
        private PaymentServiceReference.PaymentState PaymentStateField;
        
        private int RegistrerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollectionDate
        {
            get
            {
                return this.CollectionDateField;
            }
            set
            {
                this.CollectionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreditId
        {
            get
            {
                return this.CreditIdField;
            }
            set
            {
                this.CreditIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PaymentServiceReference.PaymentState PaymentState
        {
            get
            {
                return this.PaymentStateField;
            }
            set
            {
                this.PaymentStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegistrerId
        {
            get
            {
                return this.RegistrerIdField;
            }
            set
            {
                this.RegistrerIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentState", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public enum PaymentState : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Collected = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotCollected = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaymentServiceReference.IPaymentService")]
    public interface IPaymentService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetPaymentLayout", ReplyAction="http://tempuri.org/IPaymentService/GetPaymentLayoutResponse")]
        PaymentServiceReference.ResponseWithContentOfArrayOfPaymentLayoutDC1nk_PiFui GetPaymentLayout(string firstDate, string endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetPaymentLayout", ReplyAction="http://tempuri.org/IPaymentService/GetPaymentLayoutResponse")]
        System.Threading.Tasks.Task<PaymentServiceReference.ResponseWithContentOfArrayOfPaymentLayoutDC1nk_PiFui> GetPaymentLayoutAsync(string firstDate, string endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/UpdatePaymentState", ReplyAction="http://tempuri.org/IPaymentService/UpdatePaymentStateResponse")]
        PaymentServiceReference.Response UpdatePaymentState(PaymentServiceReference.PaymentDC payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/UpdatePaymentState", ReplyAction="http://tempuri.org/IPaymentService/UpdatePaymentStateResponse")]
        System.Threading.Tasks.Task<PaymentServiceReference.Response> UpdatePaymentStateAsync(PaymentServiceReference.PaymentDC payment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IPaymentServiceChannel : PaymentServiceReference.IPaymentService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class PaymentServiceClient : System.ServiceModel.ClientBase<PaymentServiceReference.IPaymentService>, PaymentServiceReference.IPaymentService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PaymentServiceClient() : 
                base(PaymentServiceClient.GetDefaultBinding(), PaymentServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPaymentService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PaymentServiceClient.GetBindingForEndpoint(endpointConfiguration), PaymentServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PaymentServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PaymentServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PaymentServiceReference.ResponseWithContentOfArrayOfPaymentLayoutDC1nk_PiFui GetPaymentLayout(string firstDate, string endDate)
        {
            return base.Channel.GetPaymentLayout(firstDate, endDate);
        }
        
        public System.Threading.Tasks.Task<PaymentServiceReference.ResponseWithContentOfArrayOfPaymentLayoutDC1nk_PiFui> GetPaymentLayoutAsync(string firstDate, string endDate)
        {
            return base.Channel.GetPaymentLayoutAsync(firstDate, endDate);
        }
        
        public PaymentServiceReference.Response UpdatePaymentState(PaymentServiceReference.PaymentDC payment)
        {
            return base.Channel.UpdatePaymentState(payment);
        }
        
        public System.Threading.Tasks.Task<PaymentServiceReference.Response> UpdatePaymentStateAsync(PaymentServiceReference.PaymentDC payment)
        {
            return base.Channel.UpdatePaymentStateAsync(payment);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPaymentService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPaymentService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:5001/PaymentService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PaymentServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPaymentService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PaymentServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPaymentService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPaymentService,
        }
    }
}
