//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditRequestDC", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class CreditRequestDC : object
    {
        
        private CreditServiceReference.CreditDC CreditField;
        
        private CreditServiceReference.CreditDocumentDC[] DocumentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreditServiceReference.CreditDC Credit
        {
            get
            {
                return this.CreditField;
            }
            set
            {
                this.CreditField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreditServiceReference.CreditDocumentDC[] Documents
        {
            get
            {
                return this.DocumentsField;
            }
            set
            {
                this.DocumentsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditDC", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class CreditDC : object
    {
        
        private string BeneficiaryIdField;
        
        private int CapitalField;
        
        private int ConditionIdField;
        
        private int DurationField;
        
        private int IdField;
        
        private int RegistrerIdField;
        
        private string RegistryDateField;
        
        private string StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BeneficiaryId
        {
            get
            {
                return this.BeneficiaryIdField;
            }
            set
            {
                this.BeneficiaryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Capital
        {
            get
            {
                return this.CapitalField;
            }
            set
            {
                this.CapitalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConditionId
        {
            get
            {
                return this.ConditionIdField;
            }
            set
            {
                this.ConditionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duration
        {
            get
            {
                return this.DurationField;
            }
            set
            {
                this.DurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegistrerId
        {
            get
            {
                return this.RegistrerIdField;
            }
            set
            {
                this.RegistrerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistryDate
        {
            get
            {
                return this.RegistryDateField;
            }
            set
            {
                this.RegistryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditDocumentDC", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class CreditDocumentDC : object
    {
        
        private int DocumentationIdField;
        
        private byte[] FileField;
        
        private int IdField;
        
        private string NameField;
        
        private int RegistrerIdField;
        
        private string RegistryDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentationId
        {
            get
            {
                return this.DocumentationIdField;
            }
            set
            {
                this.DocumentationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] File
        {
            get
            {
                return this.FileField;
            }
            set
            {
                this.FileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegistrerId
        {
            get
            {
                return this.RegistrerIdField;
            }
            set
            {
                this.RegistrerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistryDate
        {
            get
            {
                return this.RegistryDateField;
            }
            set
            {
                this.RegistryDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreditServiceReference.ResponseWithContentOfArrayOfCreditDC1nk_PiFui))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreditServiceReference.ResponseWithContentOfArrayOfCreditRequestSummaryDC1nk_PiFui))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreditServiceReference.ResponseWithContentOfCreditDC1nk_PiFui))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreditServiceReference.ResponseWithContentOfArrayOfCreditDocumentDC1nk_PiFui))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreditServiceReference.ResponseWithContentOfCreditPaymentDC1nk_PiFui))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreditServiceReference.ResponseWithContentOfint))]
    public partial class Response : object
    {
        
        private string MessageField;
        
        private int StatusCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithContentOfArrayOfCreditDC1nk_PiFui", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class ResponseWithContentOfArrayOfCreditDC1nk_PiFui : CreditServiceReference.Response
    {
        
        private CreditServiceReference.CreditDC[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreditServiceReference.CreditDC[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithContentOfArrayOfCreditRequestSummaryDC1nk_PiFui", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class ResponseWithContentOfArrayOfCreditRequestSummaryDC1nk_PiFui : CreditServiceReference.Response
    {
        
        private CreditServiceReference.CreditRequestSummaryDC[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreditServiceReference.CreditRequestSummaryDC[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithContentOfCreditDC1nk_PiFui", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class ResponseWithContentOfCreditDC1nk_PiFui : CreditServiceReference.Response
    {
        
        private CreditServiceReference.CreditDC DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreditServiceReference.CreditDC Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithContentOfArrayOfCreditDocumentDC1nk_PiFui", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class ResponseWithContentOfArrayOfCreditDocumentDC1nk_PiFui : CreditServiceReference.Response
    {
        
        private CreditServiceReference.CreditDocumentDC[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreditServiceReference.CreditDocumentDC[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithContentOfCreditPaymentDC1nk_PiFui", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class ResponseWithContentOfCreditPaymentDC1nk_PiFui : CreditServiceReference.Response
    {
        
        private CreditServiceReference.CreditPaymentDC DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreditServiceReference.CreditPaymentDC Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithContentOfint", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class ResponseWithContentOfint : CreditServiceReference.Response
    {
        
        private int DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditRequestSummaryDC", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class CreditRequestSummaryDC : object
    {
        
        private int CapitalField;
        
        private string ClientNameField;
        
        private int DurationField;
        
        private int IdField;
        
        private int InterestRateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Capital
        {
            get
            {
                return this.CapitalField;
            }
            set
            {
                this.CapitalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName
        {
            get
            {
                return this.ClientNameField;
            }
            set
            {
                this.ClientNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duration
        {
            get
            {
                return this.DurationField;
            }
            set
            {
                this.DurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InterestRate
        {
            get
            {
                return this.InterestRateField;
            }
            set
            {
                this.InterestRateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditPaymentDC", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class CreditPaymentDC : object
    {
        
        private int IVAField;
        
        private string beneficiaryField;
        
        private int capitalField;
        
        private int conditionIdField;
        
        private byte durationField;
        
        private int idField;
        
        private int interestRateField;
        
        private int paymentsPerMonthField;
        
        private int registrerField;
        
        private System.DateTime registryDateField;
        
        private string stateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IVA
        {
            get
            {
                return this.IVAField;
            }
            set
            {
                this.IVAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string beneficiary
        {
            get
            {
                return this.beneficiaryField;
            }
            set
            {
                this.beneficiaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int capital
        {
            get
            {
                return this.capitalField;
            }
            set
            {
                this.capitalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int conditionId
        {
            get
            {
                return this.conditionIdField;
            }
            set
            {
                this.conditionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int interestRate
        {
            get
            {
                return this.interestRateField;
            }
            set
            {
                this.interestRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int paymentsPerMonth
        {
            get
            {
                return this.paymentsPerMonthField;
            }
            set
            {
                this.paymentsPerMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int registrer
        {
            get
            {
                return this.registrerField;
            }
            set
            {
                this.registrerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime registryDate
        {
            get
            {
                return this.registryDateField;
            }
            set
            {
                this.registryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreditServiceReference.ICreditService")]
    public interface ICreditService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditService/AddCreditRequest", ReplyAction="http://tempuri.org/ICreditService/AddCreditRequestResponse")]
        CreditServiceReference.ResponseWithContentOfint AddCreditRequest(CreditServiceReference.CreditRequestDC request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditService/AddCreditRequest", ReplyAction="http://tempuri.org/ICreditService/AddCreditRequestResponse")]
        System.Threading.Tasks.Task<CreditServiceReference.ResponseWithContentOfint> AddCreditRequestAsync(CreditServiceReference.CreditRequestDC request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditService/GetActiveCredits", ReplyAction="http://tempuri.org/ICreditService/GetActiveCreditsResponse")]
        CreditServiceReference.ResponseWithContentOfArrayOfCreditDC1nk_PiFui GetActiveCredits();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditService/GetActiveCredits", ReplyAction="http://tempuri.org/ICreditService/GetActiveCreditsResponse")]
        System.Threading.Tasks.Task<CreditServiceReference.ResponseWithContentOfArrayOfCreditDC1nk_PiFui> GetActiveCreditsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditService/GetCreditsByBeneficiary", ReplyAction="http://tempuri.org/ICreditService/GetCreditsByBeneficiaryResponse")]
        CreditServiceReference.ResponseWithContentOfArrayOfCreditDC1nk_PiFui GetCreditsByBeneficiary(string beneficiaryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditService/GetCreditsByBeneficiary", ReplyAction="http://tempuri.org/ICreditService/GetCreditsByBeneficiaryResponse")]
        System.Threading.Tasks.Task<CreditServiceReference.ResponseWithContentOfArrayOfCreditDC1nk_PiFui> GetCreditsByBeneficiaryAsync(string beneficiaryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditService/GetCreditRequests", ReplyAction="http://tempuri.org/ICreditService/GetCreditRequestsResponse")]
        CreditServiceReference.ResponseWithContentOfArrayOfCreditRequestSummaryDC1nk_PiFui GetCreditRequests();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditService/GetCreditRequests", ReplyAction="http://tempuri.org/ICreditService/GetCreditRequestsResponse")]
        System.Threading.Tasks.Task<CreditServiceReference.ResponseWithContentOfArrayOfCreditRequestSummaryDC1nk_PiFui> GetCreditRequestsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditService/DetermineRequest", ReplyAction="http://tempuri.org/ICreditService/DetermineRequestResponse")]
        CreditServiceReference.Response DetermineRequest(int requestId, bool granted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditService/DetermineRequest", ReplyAction="http://tempuri.org/ICreditService/DetermineRequestResponse")]
        System.Threading.Tasks.Task<CreditServiceReference.Response> DetermineRequestAsync(int requestId, bool granted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditService/GetCredit", ReplyAction="http://tempuri.org/ICreditService/GetCreditResponse")]
        CreditServiceReference.ResponseWithContentOfCreditDC1nk_PiFui GetCredit(int creditId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditService/GetCredit", ReplyAction="http://tempuri.org/ICreditService/GetCreditResponse")]
        System.Threading.Tasks.Task<CreditServiceReference.ResponseWithContentOfCreditDC1nk_PiFui> GetCreditAsync(int creditId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditService/GetCreditsDocuments", ReplyAction="http://tempuri.org/ICreditService/GetCreditsDocumentsResponse")]
        CreditServiceReference.ResponseWithContentOfArrayOfCreditDocumentDC1nk_PiFui GetCreditsDocuments(int creditId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditService/GetCreditsDocuments", ReplyAction="http://tempuri.org/ICreditService/GetCreditsDocumentsResponse")]
        System.Threading.Tasks.Task<CreditServiceReference.ResponseWithContentOfArrayOfCreditDocumentDC1nk_PiFui> GetCreditsDocumentsAsync(int creditId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditService/UpdateCreditDocuments", ReplyAction="http://tempuri.org/ICreditService/UpdateCreditDocumentsResponse")]
        CreditServiceReference.Response UpdateCreditDocuments(int creditId, CreditServiceReference.CreditDocumentDC[] documents);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditService/UpdateCreditDocuments", ReplyAction="http://tempuri.org/ICreditService/UpdateCreditDocumentsResponse")]
        System.Threading.Tasks.Task<CreditServiceReference.Response> UpdateCreditDocumentsAsync(int creditId, CreditServiceReference.CreditDocumentDC[] documents);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditService/GetPaymentInfo", ReplyAction="http://tempuri.org/ICreditService/GetPaymentInfoResponse")]
        CreditServiceReference.ResponseWithContentOfCreditPaymentDC1nk_PiFui GetPaymentInfo(int creditId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditService/GetPaymentInfo", ReplyAction="http://tempuri.org/ICreditService/GetPaymentInfoResponse")]
        System.Threading.Tasks.Task<CreditServiceReference.ResponseWithContentOfCreditPaymentDC1nk_PiFui> GetPaymentInfoAsync(int creditId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ICreditServiceChannel : CreditServiceReference.ICreditService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class CreditServiceClient : System.ServiceModel.ClientBase<CreditServiceReference.ICreditService>, CreditServiceReference.ICreditService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CreditServiceClient() : 
                base(CreditServiceClient.GetDefaultBinding(), CreditServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICreditService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreditServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CreditServiceClient.GetBindingForEndpoint(endpointConfiguration), CreditServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreditServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CreditServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreditServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CreditServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreditServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public CreditServiceReference.ResponseWithContentOfint AddCreditRequest(CreditServiceReference.CreditRequestDC request)
        {
            return base.Channel.AddCreditRequest(request);
        }
        
        public System.Threading.Tasks.Task<CreditServiceReference.ResponseWithContentOfint> AddCreditRequestAsync(CreditServiceReference.CreditRequestDC request)
        {
            return base.Channel.AddCreditRequestAsync(request);
        }
        
        public CreditServiceReference.ResponseWithContentOfArrayOfCreditDC1nk_PiFui GetActiveCredits()
        {
            return base.Channel.GetActiveCredits();
        }
        
        public System.Threading.Tasks.Task<CreditServiceReference.ResponseWithContentOfArrayOfCreditDC1nk_PiFui> GetActiveCreditsAsync()
        {
            return base.Channel.GetActiveCreditsAsync();
        }
        
        public CreditServiceReference.ResponseWithContentOfArrayOfCreditDC1nk_PiFui GetCreditsByBeneficiary(string beneficiaryId)
        {
            return base.Channel.GetCreditsByBeneficiary(beneficiaryId);
        }
        
        public System.Threading.Tasks.Task<CreditServiceReference.ResponseWithContentOfArrayOfCreditDC1nk_PiFui> GetCreditsByBeneficiaryAsync(string beneficiaryId)
        {
            return base.Channel.GetCreditsByBeneficiaryAsync(beneficiaryId);
        }
        
        public CreditServiceReference.ResponseWithContentOfArrayOfCreditRequestSummaryDC1nk_PiFui GetCreditRequests()
        {
            return base.Channel.GetCreditRequests();
        }
        
        public System.Threading.Tasks.Task<CreditServiceReference.ResponseWithContentOfArrayOfCreditRequestSummaryDC1nk_PiFui> GetCreditRequestsAsync()
        {
            return base.Channel.GetCreditRequestsAsync();
        }
        
        public CreditServiceReference.Response DetermineRequest(int requestId, bool granted)
        {
            return base.Channel.DetermineRequest(requestId, granted);
        }
        
        public System.Threading.Tasks.Task<CreditServiceReference.Response> DetermineRequestAsync(int requestId, bool granted)
        {
            return base.Channel.DetermineRequestAsync(requestId, granted);
        }
        
        public CreditServiceReference.ResponseWithContentOfCreditDC1nk_PiFui GetCredit(int creditId)
        {
            return base.Channel.GetCredit(creditId);
        }
        
        public System.Threading.Tasks.Task<CreditServiceReference.ResponseWithContentOfCreditDC1nk_PiFui> GetCreditAsync(int creditId)
        {
            return base.Channel.GetCreditAsync(creditId);
        }
        
        public CreditServiceReference.ResponseWithContentOfArrayOfCreditDocumentDC1nk_PiFui GetCreditsDocuments(int creditId)
        {
            return base.Channel.GetCreditsDocuments(creditId);
        }
        
        public System.Threading.Tasks.Task<CreditServiceReference.ResponseWithContentOfArrayOfCreditDocumentDC1nk_PiFui> GetCreditsDocumentsAsync(int creditId)
        {
            return base.Channel.GetCreditsDocumentsAsync(creditId);
        }
        
        public CreditServiceReference.Response UpdateCreditDocuments(int creditId, CreditServiceReference.CreditDocumentDC[] documents)
        {
            return base.Channel.UpdateCreditDocuments(creditId, documents);
        }
        
        public System.Threading.Tasks.Task<CreditServiceReference.Response> UpdateCreditDocumentsAsync(int creditId, CreditServiceReference.CreditDocumentDC[] documents)
        {
            return base.Channel.UpdateCreditDocumentsAsync(creditId, documents);
        }
        
        public CreditServiceReference.ResponseWithContentOfCreditPaymentDC1nk_PiFui GetPaymentInfo(int creditId)
        {
            return base.Channel.GetPaymentInfo(creditId);
        }
        
        public System.Threading.Tasks.Task<CreditServiceReference.ResponseWithContentOfCreditPaymentDC1nk_PiFui> GetPaymentInfoAsync(int creditId)
        {
            return base.Channel.GetPaymentInfoAsync(creditId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICreditService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICreditService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:5001/CreditService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CreditServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICreditService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CreditServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICreditService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICreditService,
        }
    }
}
