//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financiera_GUI {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotificationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Financiera_GUI.NotificationMessages", typeof(NotificationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El credito enviado no existe.
        /// </summary>
        internal static string EvaluationEmptyCredit {
            get {
                return ResourceManager.GetString("EvaluationEmptyCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El crédito no se ingresó o es  Inválido..
        /// </summary>
        internal static string EvaluationInvalidCredit {
            get {
                return ResourceManager.GetString("EvaluationInvalidCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los campos son obligatorios.
        /// </summary>
        internal static string GlobalEmptyFields {
            get {
                return ResourceManager.GetString("GlobalEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado. Intente más tarde por favor.
        /// </summary>
        internal static string GlobalInternalError {
            get {
                return ResourceManager.GetString("GlobalInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos inválidos, Por favor verifique la información.
        /// </summary>
        internal static string GlobalInvalidFields {
            get {
                return ResourceManager.GetString("GlobalInvalidFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro se ha completado exitosamente.
        /// </summary>
        internal static string GlobalRegistrationSuccess {
            get {
                return ResourceManager.GetString("GlobalRegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha actualizado el estado exitosamente.
        /// </summary>
        internal static string GlobalStatusUpdateSuccess {
            get {
                return ResourceManager.GetString("GlobalStatusUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se han actualizado los datos exitosamente.
        /// </summary>
        internal static string GlobalUpdateSuccess {
            get {
                return ResourceManager.GetString("GlobalUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una sesión activa con este usuario.
        /// </summary>
        internal static string LoginActiveSessions {
            get {
                return ResourceManager.GetString("LoginActiveSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no encontrado o no existe.
        /// </summary>
        internal static string LoginUserNotFund {
            get {
                return ResourceManager.GetString("LoginUserNotFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrecta.
        /// </summary>
        internal static string LoginWrongCredentials {
            get {
                return ResourceManager.GetString("LoginWrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible generar el layout de cobro. Contacte a soporte técnico si el problema persiste..
        /// </summary>
        internal static string PaymentLayoutGenerationFailed {
            get {
                return ResourceManager.GetString("PaymentLayoutGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha guardado correctamente el layout de cobro en su carpeta de Descargas..
        /// </summary>
        internal static string PaymentLayoutGenerationSuccessful {
            get {
                return ResourceManager.GetString("PaymentLayoutGenerationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Politica ya registrada.
        /// </summary>
        internal static string PolicyDuplicated {
            get {
                return ResourceManager.GetString("PolicyDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró la politica seleccionada.
        /// </summary>
        internal static string PolicyNotFound {
            get {
                return ResourceManager.GetString("PolicyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complete todos los campos.
        /// </summary>
        internal static string ResetEmptyFields {
            get {
                return ResourceManager.GetString("ResetEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de verificación incorrecto.
        /// </summary>
        internal static string ResetIncorrectCode {
            get {
                return ResourceManager.GetString("ResetIncorrectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no encontrado.
        /// </summary>
        internal static string ResetInvalidCredentials {
            get {
                return ResourceManager.GetString("ResetInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La búsqueda no tuvo resultados.
        /// </summary>
        internal static string SearchNotFound {
            get {
                return ResourceManager.GetString("SearchNotFound", resourceCulture);
            }
        }
    }
}
