//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CatalogServiceReference.ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CatalogServiceReference.ResponseWithContentOfArrayOfSubsidiaryDC1nk_PiFui))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui))]
    public partial class Response : object
    {
        
        private string MessageField;
        
        private int StatusCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui : CatalogServiceReference.Response
    {
        
        private CatalogServiceReference.CreditConditionDC[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.CreditConditionDC[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithContentOfArrayOfSubsidiaryDC1nk_PiFui", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class ResponseWithContentOfArrayOfSubsidiaryDC1nk_PiFui : CatalogServiceReference.Response
    {
        
        private CatalogServiceReference.SubsidiaryDC[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.SubsidiaryDC[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui : CatalogServiceReference.Response
    {
        
        private CatalogServiceReference.RequiredDocumentDC[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.RequiredDocumentDC[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequiredDocumentDC", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class RequiredDocumentDC : object
    {
        
        private string FileTypeField;
        
        private int IdField;
        
        private string NameField;
        
        private bool StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileType
        {
            get
            {
                return this.FileTypeField;
            }
            set
            {
                this.FileTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditConditionDC", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class CreditConditionDC : object
    {
        
        private int IVAField;
        
        private int IdField;
        
        private int InterestRateField;
        
        private int PaymentsPerMonthField;
        
        private int RegistrerIdField;
        
        private bool StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IVA
        {
            get
            {
                return this.IVAField;
            }
            set
            {
                this.IVAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InterestRate
        {
            get
            {
                return this.InterestRateField;
            }
            set
            {
                this.InterestRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentsPerMonth
        {
            get
            {
                return this.PaymentsPerMonthField;
            }
            set
            {
                this.PaymentsPerMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegistrerId
        {
            get
            {
                return this.RegistrerIdField;
            }
            set
            {
                this.RegistrerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubsidiaryDC", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class SubsidiaryDC : object
    {
        
        private string AddressField;
        
        private int IdField;
        
        private bool StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CatalogServiceReference.ICatalogService")]
    public interface ICatalogService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetRequiredDocumentationByPaginationNext", ReplyAction="http://tempuri.org/ICatalogService/GetRequiredDocumentationByPaginationNextRespon" +
            "se")]
        CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui GetRequiredDocumentationByPaginationNext(int pageSize, int lastId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetRequiredDocumentationByPaginationNext", ReplyAction="http://tempuri.org/ICatalogService/GetRequiredDocumentationByPaginationNextRespon" +
            "se")]
        System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui> GetRequiredDocumentationByPaginationNextAsync(int pageSize, int lastId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetRequiredDocumentationByPaginationPrevious", ReplyAction="http://tempuri.org/ICatalogService/GetRequiredDocumentationByPaginationPreviousRe" +
            "sponse")]
        CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui GetRequiredDocumentationByPaginationPrevious(int pageSize, int firstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetRequiredDocumentationByPaginationPrevious", ReplyAction="http://tempuri.org/ICatalogService/GetRequiredDocumentationByPaginationPreviousRe" +
            "sponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui> GetRequiredDocumentationByPaginationPreviousAsync(int pageSize, int firstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetActiveRequiredDocumentation", ReplyAction="http://tempuri.org/ICatalogService/GetActiveRequiredDocumentationResponse")]
        CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui GetActiveRequiredDocumentation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetActiveRequiredDocumentation", ReplyAction="http://tempuri.org/ICatalogService/GetActiveRequiredDocumentationResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui> GetActiveRequiredDocumentationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/AddRequiredDocument", ReplyAction="http://tempuri.org/ICatalogService/AddRequiredDocumentResponse")]
        CatalogServiceReference.Response AddRequiredDocument(CatalogServiceReference.RequiredDocumentDC requiredDocument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/AddRequiredDocument", ReplyAction="http://tempuri.org/ICatalogService/AddRequiredDocumentResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> AddRequiredDocumentAsync(CatalogServiceReference.RequiredDocumentDC requiredDocument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateRequiredDocument", ReplyAction="http://tempuri.org/ICatalogService/UpdateRequiredDocumentResponse")]
        CatalogServiceReference.Response UpdateRequiredDocument(CatalogServiceReference.RequiredDocumentDC requiredDocument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateRequiredDocument", ReplyAction="http://tempuri.org/ICatalogService/UpdateRequiredDocumentResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateRequiredDocumentAsync(CatalogServiceReference.RequiredDocumentDC requiredDocument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateRequiredDocumentState", ReplyAction="http://tempuri.org/ICatalogService/UpdateRequiredDocumentStateResponse")]
        CatalogServiceReference.Response UpdateRequiredDocumentState(int id, bool isActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateRequiredDocumentState", ReplyAction="http://tempuri.org/ICatalogService/UpdateRequiredDocumentStateResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateRequiredDocumentStateAsync(int id, bool isActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetCreditConditionsByPagination", ReplyAction="http://tempuri.org/ICatalogService/GetCreditConditionsByPaginationResponse")]
        CatalogServiceReference.ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui GetCreditConditionsByPagination(int pageSize, int markId, bool next);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetCreditConditionsByPagination", ReplyAction="http://tempuri.org/ICatalogService/GetCreditConditionsByPaginationResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui> GetCreditConditionsByPaginationAsync(int pageSize, int markId, bool next);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetActiveCreditConditions", ReplyAction="http://tempuri.org/ICatalogService/GetActiveCreditConditionsResponse")]
        CatalogServiceReference.ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui GetActiveCreditConditions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetActiveCreditConditions", ReplyAction="http://tempuri.org/ICatalogService/GetActiveCreditConditionsResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui> GetActiveCreditConditionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/AddCreditCondition", ReplyAction="http://tempuri.org/ICatalogService/AddCreditConditionResponse")]
        CatalogServiceReference.Response AddCreditCondition(CatalogServiceReference.CreditConditionDC creditCondition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/AddCreditCondition", ReplyAction="http://tempuri.org/ICatalogService/AddCreditConditionResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> AddCreditConditionAsync(CatalogServiceReference.CreditConditionDC creditCondition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateCreditCondition", ReplyAction="http://tempuri.org/ICatalogService/UpdateCreditConditionResponse")]
        CatalogServiceReference.Response UpdateCreditCondition(CatalogServiceReference.CreditConditionDC creditCondition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateCreditCondition", ReplyAction="http://tempuri.org/ICatalogService/UpdateCreditConditionResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateCreditConditionAsync(CatalogServiceReference.CreditConditionDC creditCondition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateCreditConditionState", ReplyAction="http://tempuri.org/ICatalogService/UpdateCreditConditionStateResponse")]
        CatalogServiceReference.Response UpdateCreditConditionState(int id, bool state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateCreditConditionState", ReplyAction="http://tempuri.org/ICatalogService/UpdateCreditConditionStateResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateCreditConditionStateAsync(int id, bool state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetSubsidiaries", ReplyAction="http://tempuri.org/ICatalogService/GetSubsidiariesResponse")]
        CatalogServiceReference.ResponseWithContentOfArrayOfSubsidiaryDC1nk_PiFui GetSubsidiaries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetSubsidiaries", ReplyAction="http://tempuri.org/ICatalogService/GetSubsidiariesResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfSubsidiaryDC1nk_PiFui> GetSubsidiariesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/AddSubsidiary", ReplyAction="http://tempuri.org/ICatalogService/AddSubsidiaryResponse")]
        CatalogServiceReference.Response AddSubsidiary(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/AddSubsidiary", ReplyAction="http://tempuri.org/ICatalogService/AddSubsidiaryResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> AddSubsidiaryAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateSubsidiaryAddress", ReplyAction="http://tempuri.org/ICatalogService/UpdateSubsidiaryAddressResponse")]
        CatalogServiceReference.Response UpdateSubsidiaryAddress(int id, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateSubsidiaryAddress", ReplyAction="http://tempuri.org/ICatalogService/UpdateSubsidiaryAddressResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateSubsidiaryAddressAsync(int id, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateSubsidiaryState", ReplyAction="http://tempuri.org/ICatalogService/UpdateSubsidiaryStateResponse")]
        CatalogServiceReference.Response UpdateSubsidiaryState(int id, bool activeSubsidiary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateSubsidiaryState", ReplyAction="http://tempuri.org/ICatalogService/UpdateSubsidiaryStateResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateSubsidiaryStateAsync(int id, bool activeSubsidiary);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ICatalogServiceChannel : CatalogServiceReference.ICatalogService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class CatalogServiceClient : System.ServiceModel.ClientBase<CatalogServiceReference.ICatalogService>, CatalogServiceReference.ICatalogService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CatalogServiceClient() : 
                base(CatalogServiceClient.GetDefaultBinding(), CatalogServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICatalogService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CatalogServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CatalogServiceClient.GetBindingForEndpoint(endpointConfiguration), CatalogServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CatalogServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CatalogServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CatalogServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CatalogServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CatalogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui GetRequiredDocumentationByPaginationNext(int pageSize, int lastId)
        {
            return base.Channel.GetRequiredDocumentationByPaginationNext(pageSize, lastId);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui> GetRequiredDocumentationByPaginationNextAsync(int pageSize, int lastId)
        {
            return base.Channel.GetRequiredDocumentationByPaginationNextAsync(pageSize, lastId);
        }
        
        public CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui GetRequiredDocumentationByPaginationPrevious(int pageSize, int firstId)
        {
            return base.Channel.GetRequiredDocumentationByPaginationPrevious(pageSize, firstId);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui> GetRequiredDocumentationByPaginationPreviousAsync(int pageSize, int firstId)
        {
            return base.Channel.GetRequiredDocumentationByPaginationPreviousAsync(pageSize, firstId);
        }
        
        public CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui GetActiveRequiredDocumentation()
        {
            return base.Channel.GetActiveRequiredDocumentation();
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui> GetActiveRequiredDocumentationAsync()
        {
            return base.Channel.GetActiveRequiredDocumentationAsync();
        }
        
        public CatalogServiceReference.Response AddRequiredDocument(CatalogServiceReference.RequiredDocumentDC requiredDocument)
        {
            return base.Channel.AddRequiredDocument(requiredDocument);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> AddRequiredDocumentAsync(CatalogServiceReference.RequiredDocumentDC requiredDocument)
        {
            return base.Channel.AddRequiredDocumentAsync(requiredDocument);
        }
        
        public CatalogServiceReference.Response UpdateRequiredDocument(CatalogServiceReference.RequiredDocumentDC requiredDocument)
        {
            return base.Channel.UpdateRequiredDocument(requiredDocument);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateRequiredDocumentAsync(CatalogServiceReference.RequiredDocumentDC requiredDocument)
        {
            return base.Channel.UpdateRequiredDocumentAsync(requiredDocument);
        }
        
        public CatalogServiceReference.Response UpdateRequiredDocumentState(int id, bool isActive)
        {
            return base.Channel.UpdateRequiredDocumentState(id, isActive);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateRequiredDocumentStateAsync(int id, bool isActive)
        {
            return base.Channel.UpdateRequiredDocumentStateAsync(id, isActive);
        }
        
        public CatalogServiceReference.ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui GetCreditConditionsByPagination(int pageSize, int markId, bool next)
        {
            return base.Channel.GetCreditConditionsByPagination(pageSize, markId, next);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui> GetCreditConditionsByPaginationAsync(int pageSize, int markId, bool next)
        {
            return base.Channel.GetCreditConditionsByPaginationAsync(pageSize, markId, next);
        }
        
        public CatalogServiceReference.ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui GetActiveCreditConditions()
        {
            return base.Channel.GetActiveCreditConditions();
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui> GetActiveCreditConditionsAsync()
        {
            return base.Channel.GetActiveCreditConditionsAsync();
        }
        
        public CatalogServiceReference.Response AddCreditCondition(CatalogServiceReference.CreditConditionDC creditCondition)
        {
            return base.Channel.AddCreditCondition(creditCondition);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> AddCreditConditionAsync(CatalogServiceReference.CreditConditionDC creditCondition)
        {
            return base.Channel.AddCreditConditionAsync(creditCondition);
        }
        
        public CatalogServiceReference.Response UpdateCreditCondition(CatalogServiceReference.CreditConditionDC creditCondition)
        {
            return base.Channel.UpdateCreditCondition(creditCondition);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateCreditConditionAsync(CatalogServiceReference.CreditConditionDC creditCondition)
        {
            return base.Channel.UpdateCreditConditionAsync(creditCondition);
        }
        
        public CatalogServiceReference.Response UpdateCreditConditionState(int id, bool state)
        {
            return base.Channel.UpdateCreditConditionState(id, state);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateCreditConditionStateAsync(int id, bool state)
        {
            return base.Channel.UpdateCreditConditionStateAsync(id, state);
        }
        
        public CatalogServiceReference.ResponseWithContentOfArrayOfSubsidiaryDC1nk_PiFui GetSubsidiaries()
        {
            return base.Channel.GetSubsidiaries();
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfSubsidiaryDC1nk_PiFui> GetSubsidiariesAsync()
        {
            return base.Channel.GetSubsidiariesAsync();
        }
        
        public CatalogServiceReference.Response AddSubsidiary(string address)
        {
            return base.Channel.AddSubsidiary(address);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> AddSubsidiaryAsync(string address)
        {
            return base.Channel.AddSubsidiaryAsync(address);
        }
        
        public CatalogServiceReference.Response UpdateSubsidiaryAddress(int id, string address)
        {
            return base.Channel.UpdateSubsidiaryAddress(id, address);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateSubsidiaryAddressAsync(int id, string address)
        {
            return base.Channel.UpdateSubsidiaryAddressAsync(id, address);
        }
        
        public CatalogServiceReference.Response UpdateSubsidiaryState(int id, bool activeSubsidiary)
        {
            return base.Channel.UpdateSubsidiaryState(id, activeSubsidiary);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateSubsidiaryStateAsync(int id, bool activeSubsidiary)
        {
            return base.Channel.UpdateSubsidiaryStateAsync(id, activeSubsidiary);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICatalogService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICatalogService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:5001/CatalogService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CatalogServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICatalogService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CatalogServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICatalogService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICatalogService,
        }
    }
}
