//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CatalogServiceReference.ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CatalogServiceReference.ResponseWithContentOfArrayOfSubsidiaryDC1nk_PiFui))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CatalogServiceReference.ResponseWithContentOfArrayOfCreditPolicyDC1nk_PiFui))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui))]
    public partial class Response : object
    {
        
        private string MessageField;
        
        private int StatusCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui : CatalogServiceReference.Response
    {
        
        private CatalogServiceReference.CreditConditionDC[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.CreditConditionDC[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithContentOfArrayOfSubsidiaryDC1nk_PiFui", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class ResponseWithContentOfArrayOfSubsidiaryDC1nk_PiFui : CatalogServiceReference.Response
    {
        
        private CatalogServiceReference.SubsidiaryDC[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.SubsidiaryDC[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithContentOfArrayOfCreditPolicyDC1nk_PiFui", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class ResponseWithContentOfArrayOfCreditPolicyDC1nk_PiFui : CatalogServiceReference.Response
    {
        
        private CatalogServiceReference.CreditPolicyDC[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.CreditPolicyDC[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui : CatalogServiceReference.Response
    {
        
        private CatalogServiceReference.RequiredDocumentDC[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.RequiredDocumentDC[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequiredDocumentDC", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class RequiredDocumentDC : object
    {
        
        private string FileTypeField;
        
        private int IdField;
        
        private string NameField;
        
        private bool StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileType
        {
            get
            {
                return this.FileTypeField;
            }
            set
            {
                this.FileTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditConditionDC", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class CreditConditionDC : object
    {
        
        private int IVAField;
        
        private int IdField;
        
        private int InterestRateField;
        
        private int PaymentsPerMonthField;
        
        private int RegistrerIdField;
        
        private bool StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IVA
        {
            get
            {
                return this.IVAField;
            }
            set
            {
                this.IVAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InterestRate
        {
            get
            {
                return this.InterestRateField;
            }
            set
            {
                this.InterestRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentsPerMonth
        {
            get
            {
                return this.PaymentsPerMonthField;
            }
            set
            {
                this.PaymentsPerMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegistrerId
        {
            get
            {
                return this.RegistrerIdField;
            }
            set
            {
                this.RegistrerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubsidiaryDC", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class SubsidiaryDC : object
    {
        
        private string AddressField;
        
        private int IdField;
        
        private bool StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditPolicyDC", Namespace="http://schemas.datacontract.org/2004/07/FinancieraServer.DataContracts")]
    public partial class CreditPolicyDC : object
    {
        
        private string DescriptionField;
        
        private CatalogServiceReference.DateOnly EffectiveDateField;
        
        private int IdField;
        
        private bool StateField;
        
        private string TitleField;
        
        private int registerField;
        
        private CatalogServiceReference.Employee registerNavigationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.DateOnly EffectiveDate
        {
            get
            {
                return this.EffectiveDateField;
            }
            set
            {
                this.EffectiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int register
        {
            get
            {
                return this.registerField;
            }
            set
            {
                this.registerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.Employee registerNavigation
        {
            get
            {
                return this.registerNavigationField;
            }
            set
            {
                this.registerNavigationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateOnly", Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial struct DateOnly
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/Data_Access.Entities")]
    public partial class Employee : object
    {
        
        private CatalogServiceReference.CreditCondition[] CreditConditionsField;
        
        private CatalogServiceReference.CreditPolicy[] CreditPoliciesField;
        
        private CatalogServiceReference.Credit[] CreditsField;
        
        private CatalogServiceReference.Document[] DocumentsField;
        
        private CatalogServiceReference.Payment[] PaymentsField;
        
        private string addressField;
        
        private CatalogServiceReference.DateOnly birthdayField;
        
        private int idField;
        
        private string mailField;
        
        private string nameField;
        
        private string passwordField;
        
        private string phoneNumberField;
        
        private string roleField;
        
        private CatalogServiceReference.Subsidiary sucursalField;
        
        private int sucursalIdField;
        
        private string userField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.CreditCondition[] CreditConditions
        {
            get
            {
                return this.CreditConditionsField;
            }
            set
            {
                this.CreditConditionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.CreditPolicy[] CreditPolicies
        {
            get
            {
                return this.CreditPoliciesField;
            }
            set
            {
                this.CreditPoliciesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.Credit[] Credits
        {
            get
            {
                return this.CreditsField;
            }
            set
            {
                this.CreditsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.Document[] Documents
        {
            get
            {
                return this.DocumentsField;
            }
            set
            {
                this.DocumentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.Payment[] Payments
        {
            get
            {
                return this.PaymentsField;
            }
            set
            {
                this.PaymentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.DateOnly birthday
        {
            get
            {
                return this.birthdayField;
            }
            set
            {
                this.birthdayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail
        {
            get
            {
                return this.mailField;
            }
            set
            {
                this.mailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.Subsidiary sucursal
        {
            get
            {
                return this.sucursalField;
            }
            set
            {
                this.sucursalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sucursalId
        {
            get
            {
                return this.sucursalIdField;
            }
            set
            {
                this.sucursalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subsidiary", Namespace="http://schemas.datacontract.org/2004/07/Data_Access.Entities")]
    public partial class Subsidiary : object
    {
        
        private string AddressField;
        
        private CatalogServiceReference.Employee[] EmployeesField;
        
        private int idField;
        
        private bool stateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.Employee[] Employees
        {
            get
            {
                return this.EmployeesField;
            }
            set
            {
                this.EmployeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCondition", Namespace="http://schemas.datacontract.org/2004/07/Data_Access.Entities")]
    public partial class CreditCondition : object
    {
        
        private CatalogServiceReference.Credit[] CreditsField;
        
        private int IVAField;
        
        private int idField;
        
        private int interestRateField;
        
        private int paymentsPerMonthField;
        
        private int registrerField;
        
        private CatalogServiceReference.Employee registrerNavigationField;
        
        private bool stateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.Credit[] Credits
        {
            get
            {
                return this.CreditsField;
            }
            set
            {
                this.CreditsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IVA
        {
            get
            {
                return this.IVAField;
            }
            set
            {
                this.IVAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int interestRate
        {
            get
            {
                return this.interestRateField;
            }
            set
            {
                this.interestRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int paymentsPerMonth
        {
            get
            {
                return this.paymentsPerMonthField;
            }
            set
            {
                this.paymentsPerMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int registrer
        {
            get
            {
                return this.registrerField;
            }
            set
            {
                this.registrerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.Employee registrerNavigation
        {
            get
            {
                return this.registrerNavigationField;
            }
            set
            {
                this.registrerNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditPolicy", Namespace="http://schemas.datacontract.org/2004/07/Data_Access.Entities")]
    public partial class CreditPolicy : object
    {
        
        private string descriptionField;
        
        private CatalogServiceReference.DateOnly effectiveDateField;
        
        private int idField;
        
        private int registrerField;
        
        private CatalogServiceReference.Employee registrerNavigationField;
        
        private bool stateField;
        
        private string titleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.DateOnly effectiveDate
        {
            get
            {
                return this.effectiveDateField;
            }
            set
            {
                this.effectiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int registrer
        {
            get
            {
                return this.registrerField;
            }
            set
            {
                this.registrerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.Employee registrerNavigation
        {
            get
            {
                return this.registrerNavigationField;
            }
            set
            {
                this.registrerNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credit", Namespace="http://schemas.datacontract.org/2004/07/Data_Access.Entities")]
    public partial class Credit : object
    {
        
        private CatalogServiceReference.Document[] DocumentsField;
        
        private CatalogServiceReference.Payment[] PaymentsField;
        
        private string beneficiaryField;
        
        private CatalogServiceReference.Client beneficiaryNavigationField;
        
        private int capitalField;
        
        private CatalogServiceReference.CreditCondition conditionField;
        
        private int conditionIdField;
        
        private byte durationField;
        
        private int idField;
        
        private int registrerField;
        
        private CatalogServiceReference.Employee registrerNavigationField;
        
        private string stateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.Document[] Documents
        {
            get
            {
                return this.DocumentsField;
            }
            set
            {
                this.DocumentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.Payment[] Payments
        {
            get
            {
                return this.PaymentsField;
            }
            set
            {
                this.PaymentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string beneficiary
        {
            get
            {
                return this.beneficiaryField;
            }
            set
            {
                this.beneficiaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.Client beneficiaryNavigation
        {
            get
            {
                return this.beneficiaryNavigationField;
            }
            set
            {
                this.beneficiaryNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int capital
        {
            get
            {
                return this.capitalField;
            }
            set
            {
                this.capitalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.CreditCondition condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int conditionId
        {
            get
            {
                return this.conditionIdField;
            }
            set
            {
                this.conditionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int registrer
        {
            get
            {
                return this.registrerField;
            }
            set
            {
                this.registrerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.Employee registrerNavigation
        {
            get
            {
                return this.registrerNavigationField;
            }
            set
            {
                this.registrerNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://schemas.datacontract.org/2004/07/Data_Access.Entities")]
    public partial class Document : object
    {
        
        private CatalogServiceReference.Credit creditField;
        
        private int creditIdField;
        
        private CatalogServiceReference.RequiredDocumentation documentationField;
        
        private int documentationIdField;
        
        private int idField;
        
        private string nameField;
        
        private int registrerField;
        
        private CatalogServiceReference.Employee registrerNavigationField;
        
        private System.DateTime registryDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.Credit credit
        {
            get
            {
                return this.creditField;
            }
            set
            {
                this.creditField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int creditId
        {
            get
            {
                return this.creditIdField;
            }
            set
            {
                this.creditIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.RequiredDocumentation documentation
        {
            get
            {
                return this.documentationField;
            }
            set
            {
                this.documentationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int documentationId
        {
            get
            {
                return this.documentationIdField;
            }
            set
            {
                this.documentationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int registrer
        {
            get
            {
                return this.registrerField;
            }
            set
            {
                this.registrerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.Employee registrerNavigation
        {
            get
            {
                return this.registrerNavigationField;
            }
            set
            {
                this.registrerNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime registryDate
        {
            get
            {
                return this.registryDateField;
            }
            set
            {
                this.registryDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/Data_Access.Entities")]
    public partial class Payment : object
    {
        
        private decimal amountField;
        
        private CatalogServiceReference.DateOnly collectionDateField;
        
        private CatalogServiceReference.Credit creditField;
        
        private int creditIdField;
        
        private int idField;
        
        private int registrerField;
        
        private CatalogServiceReference.Employee registrerNavigationField;
        
        private string stateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.DateOnly collectionDate
        {
            get
            {
                return this.collectionDateField;
            }
            set
            {
                this.collectionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.Credit credit
        {
            get
            {
                return this.creditField;
            }
            set
            {
                this.creditField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int creditId
        {
            get
            {
                return this.creditIdField;
            }
            set
            {
                this.creditIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int registrer
        {
            get
            {
                return this.registrerField;
            }
            set
            {
                this.registrerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.Employee registrerNavigation
        {
            get
            {
                return this.registrerNavigationField;
            }
            set
            {
                this.registrerNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/Data_Access.Entities")]
    public partial class Client : object
    {
        
        private CatalogServiceReference.BankAccount[] BankAccountsField;
        
        private CatalogServiceReference.Credit[] CreditsField;
        
        private CatalogServiceReference.DateOnly birthdayField;
        
        private string houseAddressField;
        
        private string mailField;
        
        private string nameField;
        
        private string phoneNumber1Field;
        
        private string phoneNumber2Field;
        
        private string rfcField;
        
        private bool stateField;
        
        private string workAddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.BankAccount[] BankAccounts
        {
            get
            {
                return this.BankAccountsField;
            }
            set
            {
                this.BankAccountsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.Credit[] Credits
        {
            get
            {
                return this.CreditsField;
            }
            set
            {
                this.CreditsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.DateOnly birthday
        {
            get
            {
                return this.birthdayField;
            }
            set
            {
                this.birthdayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string houseAddress
        {
            get
            {
                return this.houseAddressField;
            }
            set
            {
                this.houseAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail
        {
            get
            {
                return this.mailField;
            }
            set
            {
                this.mailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber1
        {
            get
            {
                return this.phoneNumber1Field;
            }
            set
            {
                this.phoneNumber1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber2
        {
            get
            {
                return this.phoneNumber2Field;
            }
            set
            {
                this.phoneNumber2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rfc
        {
            get
            {
                return this.rfcField;
            }
            set
            {
                this.rfcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string workAddress
        {
            get
            {
                return this.workAddressField;
            }
            set
            {
                this.workAddressField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequiredDocumentation", Namespace="http://schemas.datacontract.org/2004/07/Data_Access.Entities")]
    public partial class RequiredDocumentation : object
    {
        
        private CatalogServiceReference.Document[] DocumentsField;
        
        private string fileTypeField;
        
        private int idField;
        
        private string nameField;
        
        private bool stateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.Document[] Documents
        {
            get
            {
                return this.DocumentsField;
            }
            set
            {
                this.DocumentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fileType
        {
            get
            {
                return this.fileTypeField;
            }
            set
            {
                this.fileTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankAccount", Namespace="http://schemas.datacontract.org/2004/07/Data_Access.Entities")]
    public partial class BankAccount : object
    {
        
        private string clabeField;
        
        private CatalogServiceReference.Client clientField;
        
        private string clientIdField;
        
        private int idField;
        
        private string purposeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clabe
        {
            get
            {
                return this.clabeField;
            }
            set
            {
                this.clabeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CatalogServiceReference.Client client
        {
            get
            {
                return this.clientField;
            }
            set
            {
                this.clientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clientId
        {
            get
            {
                return this.clientIdField;
            }
            set
            {
                this.clientIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string purpose
        {
            get
            {
                return this.purposeField;
            }
            set
            {
                this.purposeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CatalogServiceReference.ICatalogService")]
    public interface ICatalogService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetRequiredDocumentationByPaginationNext", ReplyAction="http://tempuri.org/ICatalogService/GetRequiredDocumentationByPaginationNextRespon" +
            "se")]
        CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui GetRequiredDocumentationByPaginationNext(int pageSize, int lastId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetRequiredDocumentationByPaginationNext", ReplyAction="http://tempuri.org/ICatalogService/GetRequiredDocumentationByPaginationNextRespon" +
            "se")]
        System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui> GetRequiredDocumentationByPaginationNextAsync(int pageSize, int lastId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetRequiredDocumentationByPaginationPrevious", ReplyAction="http://tempuri.org/ICatalogService/GetRequiredDocumentationByPaginationPreviousRe" +
            "sponse")]
        CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui GetRequiredDocumentationByPaginationPrevious(int pageSize, int firstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetRequiredDocumentationByPaginationPrevious", ReplyAction="http://tempuri.org/ICatalogService/GetRequiredDocumentationByPaginationPreviousRe" +
            "sponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui> GetRequiredDocumentationByPaginationPreviousAsync(int pageSize, int firstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetActiveRequiredDocumentation", ReplyAction="http://tempuri.org/ICatalogService/GetActiveRequiredDocumentationResponse")]
        CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui GetActiveRequiredDocumentation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetActiveRequiredDocumentation", ReplyAction="http://tempuri.org/ICatalogService/GetActiveRequiredDocumentationResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui> GetActiveRequiredDocumentationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/AddRequiredDocument", ReplyAction="http://tempuri.org/ICatalogService/AddRequiredDocumentResponse")]
        CatalogServiceReference.Response AddRequiredDocument(CatalogServiceReference.RequiredDocumentDC requiredDocument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/AddRequiredDocument", ReplyAction="http://tempuri.org/ICatalogService/AddRequiredDocumentResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> AddRequiredDocumentAsync(CatalogServiceReference.RequiredDocumentDC requiredDocument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateRequiredDocument", ReplyAction="http://tempuri.org/ICatalogService/UpdateRequiredDocumentResponse")]
        CatalogServiceReference.Response UpdateRequiredDocument(CatalogServiceReference.RequiredDocumentDC requiredDocument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateRequiredDocument", ReplyAction="http://tempuri.org/ICatalogService/UpdateRequiredDocumentResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateRequiredDocumentAsync(CatalogServiceReference.RequiredDocumentDC requiredDocument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateRequiredDocumentState", ReplyAction="http://tempuri.org/ICatalogService/UpdateRequiredDocumentStateResponse")]
        CatalogServiceReference.Response UpdateRequiredDocumentState(int id, bool isActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateRequiredDocumentState", ReplyAction="http://tempuri.org/ICatalogService/UpdateRequiredDocumentStateResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateRequiredDocumentStateAsync(int id, bool isActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetCreditConditionsByPagination", ReplyAction="http://tempuri.org/ICatalogService/GetCreditConditionsByPaginationResponse")]
        CatalogServiceReference.ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui GetCreditConditionsByPagination(int pageSize, int markId, bool next);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetCreditConditionsByPagination", ReplyAction="http://tempuri.org/ICatalogService/GetCreditConditionsByPaginationResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui> GetCreditConditionsByPaginationAsync(int pageSize, int markId, bool next);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetActiveCreditConditions", ReplyAction="http://tempuri.org/ICatalogService/GetActiveCreditConditionsResponse")]
        CatalogServiceReference.ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui GetActiveCreditConditions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetActiveCreditConditions", ReplyAction="http://tempuri.org/ICatalogService/GetActiveCreditConditionsResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui> GetActiveCreditConditionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/AddCreditCondition", ReplyAction="http://tempuri.org/ICatalogService/AddCreditConditionResponse")]
        CatalogServiceReference.Response AddCreditCondition(CatalogServiceReference.CreditConditionDC creditCondition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/AddCreditCondition", ReplyAction="http://tempuri.org/ICatalogService/AddCreditConditionResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> AddCreditConditionAsync(CatalogServiceReference.CreditConditionDC creditCondition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateCreditCondition", ReplyAction="http://tempuri.org/ICatalogService/UpdateCreditConditionResponse")]
        CatalogServiceReference.Response UpdateCreditCondition(CatalogServiceReference.CreditConditionDC creditCondition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateCreditCondition", ReplyAction="http://tempuri.org/ICatalogService/UpdateCreditConditionResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateCreditConditionAsync(CatalogServiceReference.CreditConditionDC creditCondition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateCreditConditionState", ReplyAction="http://tempuri.org/ICatalogService/UpdateCreditConditionStateResponse")]
        CatalogServiceReference.Response UpdateCreditConditionState(int id, bool state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateCreditConditionState", ReplyAction="http://tempuri.org/ICatalogService/UpdateCreditConditionStateResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateCreditConditionStateAsync(int id, bool state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetSubsidiaries", ReplyAction="http://tempuri.org/ICatalogService/GetSubsidiariesResponse")]
        CatalogServiceReference.ResponseWithContentOfArrayOfSubsidiaryDC1nk_PiFui GetSubsidiaries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetSubsidiaries", ReplyAction="http://tempuri.org/ICatalogService/GetSubsidiariesResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfSubsidiaryDC1nk_PiFui> GetSubsidiariesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/AddSubsidiary", ReplyAction="http://tempuri.org/ICatalogService/AddSubsidiaryResponse")]
        CatalogServiceReference.Response AddSubsidiary(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/AddSubsidiary", ReplyAction="http://tempuri.org/ICatalogService/AddSubsidiaryResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> AddSubsidiaryAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateSubsidiaryAddress", ReplyAction="http://tempuri.org/ICatalogService/UpdateSubsidiaryAddressResponse")]
        CatalogServiceReference.Response UpdateSubsidiaryAddress(int id, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateSubsidiaryAddress", ReplyAction="http://tempuri.org/ICatalogService/UpdateSubsidiaryAddressResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateSubsidiaryAddressAsync(int id, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateSubsidiaryState", ReplyAction="http://tempuri.org/ICatalogService/UpdateSubsidiaryStateResponse")]
        CatalogServiceReference.Response UpdateSubsidiaryState(int id, bool activeSubsidiary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateSubsidiaryState", ReplyAction="http://tempuri.org/ICatalogService/UpdateSubsidiaryStateResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateSubsidiaryStateAsync(int id, bool activeSubsidiary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetCreditPoliciesByPagination", ReplyAction="http://tempuri.org/ICatalogService/GetCreditPoliciesByPaginationResponse")]
        CatalogServiceReference.ResponseWithContentOfArrayOfCreditPolicyDC1nk_PiFui GetCreditPoliciesByPagination(int pageSize, int markId, bool next);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/GetCreditPoliciesByPagination", ReplyAction="http://tempuri.org/ICatalogService/GetCreditPoliciesByPaginationResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfCreditPolicyDC1nk_PiFui> GetCreditPoliciesByPaginationAsync(int pageSize, int markId, bool next);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/AddCreditPolicy", ReplyAction="http://tempuri.org/ICatalogService/AddCreditPolicyResponse")]
        CatalogServiceReference.Response AddCreditPolicy(CatalogServiceReference.CreditPolicyDC newPolicy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/AddCreditPolicy", ReplyAction="http://tempuri.org/ICatalogService/AddCreditPolicyResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> AddCreditPolicyAsync(CatalogServiceReference.CreditPolicyDC newPolicy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateCreditPolicy", ReplyAction="http://tempuri.org/ICatalogService/UpdateCreditPolicyResponse")]
        CatalogServiceReference.Response UpdateCreditPolicy(CatalogServiceReference.CreditPolicyDC policyUpdated);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateCreditPolicy", ReplyAction="http://tempuri.org/ICatalogService/UpdateCreditPolicyResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateCreditPolicyAsync(CatalogServiceReference.CreditPolicyDC policyUpdated);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateCreditPolicyState", ReplyAction="http://tempuri.org/ICatalogService/UpdateCreditPolicyStateResponse")]
        CatalogServiceReference.Response UpdateCreditPolicyState(int id, bool statePolicyUpdated);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService/UpdateCreditPolicyState", ReplyAction="http://tempuri.org/ICatalogService/UpdateCreditPolicyStateResponse")]
        System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateCreditPolicyStateAsync(int id, bool statePolicyUpdated);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ICatalogServiceChannel : CatalogServiceReference.ICatalogService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class CatalogServiceClient : System.ServiceModel.ClientBase<CatalogServiceReference.ICatalogService>, CatalogServiceReference.ICatalogService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CatalogServiceClient() : 
                base(CatalogServiceClient.GetDefaultBinding(), CatalogServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICatalogService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CatalogServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CatalogServiceClient.GetBindingForEndpoint(endpointConfiguration), CatalogServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CatalogServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CatalogServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CatalogServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CatalogServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CatalogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui GetRequiredDocumentationByPaginationNext(int pageSize, int lastId)
        {
            return base.Channel.GetRequiredDocumentationByPaginationNext(pageSize, lastId);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui> GetRequiredDocumentationByPaginationNextAsync(int pageSize, int lastId)
        {
            return base.Channel.GetRequiredDocumentationByPaginationNextAsync(pageSize, lastId);
        }
        
        public CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui GetRequiredDocumentationByPaginationPrevious(int pageSize, int firstId)
        {
            return base.Channel.GetRequiredDocumentationByPaginationPrevious(pageSize, firstId);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui> GetRequiredDocumentationByPaginationPreviousAsync(int pageSize, int firstId)
        {
            return base.Channel.GetRequiredDocumentationByPaginationPreviousAsync(pageSize, firstId);
        }
        
        public CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui GetActiveRequiredDocumentation()
        {
            return base.Channel.GetActiveRequiredDocumentation();
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfRequiredDocumentDC1nk_PiFui> GetActiveRequiredDocumentationAsync()
        {
            return base.Channel.GetActiveRequiredDocumentationAsync();
        }
        
        public CatalogServiceReference.Response AddRequiredDocument(CatalogServiceReference.RequiredDocumentDC requiredDocument)
        {
            return base.Channel.AddRequiredDocument(requiredDocument);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> AddRequiredDocumentAsync(CatalogServiceReference.RequiredDocumentDC requiredDocument)
        {
            return base.Channel.AddRequiredDocumentAsync(requiredDocument);
        }
        
        public CatalogServiceReference.Response UpdateRequiredDocument(CatalogServiceReference.RequiredDocumentDC requiredDocument)
        {
            return base.Channel.UpdateRequiredDocument(requiredDocument);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateRequiredDocumentAsync(CatalogServiceReference.RequiredDocumentDC requiredDocument)
        {
            return base.Channel.UpdateRequiredDocumentAsync(requiredDocument);
        }
        
        public CatalogServiceReference.Response UpdateRequiredDocumentState(int id, bool isActive)
        {
            return base.Channel.UpdateRequiredDocumentState(id, isActive);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateRequiredDocumentStateAsync(int id, bool isActive)
        {
            return base.Channel.UpdateRequiredDocumentStateAsync(id, isActive);
        }
        
        public CatalogServiceReference.ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui GetCreditConditionsByPagination(int pageSize, int markId, bool next)
        {
            return base.Channel.GetCreditConditionsByPagination(pageSize, markId, next);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui> GetCreditConditionsByPaginationAsync(int pageSize, int markId, bool next)
        {
            return base.Channel.GetCreditConditionsByPaginationAsync(pageSize, markId, next);
        }
        
        public CatalogServiceReference.ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui GetActiveCreditConditions()
        {
            return base.Channel.GetActiveCreditConditions();
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfCreditConditionDC1nk_PiFui> GetActiveCreditConditionsAsync()
        {
            return base.Channel.GetActiveCreditConditionsAsync();
        }
        
        public CatalogServiceReference.Response AddCreditCondition(CatalogServiceReference.CreditConditionDC creditCondition)
        {
            return base.Channel.AddCreditCondition(creditCondition);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> AddCreditConditionAsync(CatalogServiceReference.CreditConditionDC creditCondition)
        {
            return base.Channel.AddCreditConditionAsync(creditCondition);
        }
        
        public CatalogServiceReference.Response UpdateCreditCondition(CatalogServiceReference.CreditConditionDC creditCondition)
        {
            return base.Channel.UpdateCreditCondition(creditCondition);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateCreditConditionAsync(CatalogServiceReference.CreditConditionDC creditCondition)
        {
            return base.Channel.UpdateCreditConditionAsync(creditCondition);
        }
        
        public CatalogServiceReference.Response UpdateCreditConditionState(int id, bool state)
        {
            return base.Channel.UpdateCreditConditionState(id, state);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateCreditConditionStateAsync(int id, bool state)
        {
            return base.Channel.UpdateCreditConditionStateAsync(id, state);
        }
        
        public CatalogServiceReference.ResponseWithContentOfArrayOfSubsidiaryDC1nk_PiFui GetSubsidiaries()
        {
            return base.Channel.GetSubsidiaries();
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfSubsidiaryDC1nk_PiFui> GetSubsidiariesAsync()
        {
            return base.Channel.GetSubsidiariesAsync();
        }
        
        public CatalogServiceReference.Response AddSubsidiary(string address)
        {
            return base.Channel.AddSubsidiary(address);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> AddSubsidiaryAsync(string address)
        {
            return base.Channel.AddSubsidiaryAsync(address);
        }
        
        public CatalogServiceReference.Response UpdateSubsidiaryAddress(int id, string address)
        {
            return base.Channel.UpdateSubsidiaryAddress(id, address);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateSubsidiaryAddressAsync(int id, string address)
        {
            return base.Channel.UpdateSubsidiaryAddressAsync(id, address);
        }
        
        public CatalogServiceReference.Response UpdateSubsidiaryState(int id, bool activeSubsidiary)
        {
            return base.Channel.UpdateSubsidiaryState(id, activeSubsidiary);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateSubsidiaryStateAsync(int id, bool activeSubsidiary)
        {
            return base.Channel.UpdateSubsidiaryStateAsync(id, activeSubsidiary);
        }
        
        public CatalogServiceReference.ResponseWithContentOfArrayOfCreditPolicyDC1nk_PiFui GetCreditPoliciesByPagination(int pageSize, int markId, bool next)
        {
            return base.Channel.GetCreditPoliciesByPagination(pageSize, markId, next);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.ResponseWithContentOfArrayOfCreditPolicyDC1nk_PiFui> GetCreditPoliciesByPaginationAsync(int pageSize, int markId, bool next)
        {
            return base.Channel.GetCreditPoliciesByPaginationAsync(pageSize, markId, next);
        }
        
        public CatalogServiceReference.Response AddCreditPolicy(CatalogServiceReference.CreditPolicyDC newPolicy)
        {
            return base.Channel.AddCreditPolicy(newPolicy);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> AddCreditPolicyAsync(CatalogServiceReference.CreditPolicyDC newPolicy)
        {
            return base.Channel.AddCreditPolicyAsync(newPolicy);
        }
        
        public CatalogServiceReference.Response UpdateCreditPolicy(CatalogServiceReference.CreditPolicyDC policyUpdated)
        {
            return base.Channel.UpdateCreditPolicy(policyUpdated);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateCreditPolicyAsync(CatalogServiceReference.CreditPolicyDC policyUpdated)
        {
            return base.Channel.UpdateCreditPolicyAsync(policyUpdated);
        }
        
        public CatalogServiceReference.Response UpdateCreditPolicyState(int id, bool statePolicyUpdated)
        {
            return base.Channel.UpdateCreditPolicyState(id, statePolicyUpdated);
        }
        
        public System.Threading.Tasks.Task<CatalogServiceReference.Response> UpdateCreditPolicyStateAsync(int id, bool statePolicyUpdated)
        {
            return base.Channel.UpdateCreditPolicyStateAsync(id, statePolicyUpdated);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICatalogService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICatalogService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:5001/CatalogService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CatalogServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICatalogService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CatalogServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICatalogService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICatalogService,
        }
    }
}
